### ISSUE TITLE
Not working properly on Laravel 8+

### ISSUE THREAD

**Issue by marcosfreitas** [zhorton34/laravel-make-facades#4]
The command `php artisan vendor:publish` is publishing the package files to a lowercase `providers` but the folder is capitalized.

![image](https://user-images.githubusercontent.com/1065688/102689702-fc843500-41de-11eb-9d9a-6208b0bc7681.png)

**Comment by MahdiPishguy** [comment]
@marcosfreitas can you resolve your problem?

**Comment by marcosfreitas** [comment]
I'm using another package but to fix it this package should be reviewed.

**Comment by zhorton34** [comment]
Closing out, pull request submitted: https://github.com/zhorton34/laravel-make-facades/pull/5
